name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Instalar Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Instalar dependencias
      run: npm ci

    - name: Ejecutar ESLint
      run: npx eslint . || true

    - name: Ejecutar pruebas
      run: npm test

    - name: Construir imagen Docker
      run: docker build -t calculador-promedios .

    - name: Guardar imagen comprimida
      run: docker save calculador-promedios | gzip > imagen.tar.gz

    - name: Subir artefacto
      uses: actions/upload-artifact@v4
      with:
        name: docker-image
        path: imagen.tar.gz

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    if: success()

    steps:
    - name: Descargar artefacto
      uses: actions/download-artifact@v4
      with:
        name: docker-image

    - name: Desplegar en EC2
      env:
        EC2_HOST: 54.227.139.149
        EC2_USER: ubuntu
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/llave-devops.pem
        chmod 600 ~/.ssh/llave-devops.pem
        gunzip -c imagen.tar.gz | docker load
        docker save calculador-promedios | gzip | ssh -o StrictHostKeyChecking=no -i ~/.ssh/llave-devops.pem $EC2_USER@$EC2_HOST "gunzip | docker load && docker stop app || true && docker rm app || true && docker run -d --name app -p 80:3000 --restart unless-stopped calculador-promedios"