name: CI/CD Calculador Promedios

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Auditoria de Seguridad (DevSecOps)
        run: npm audit --audit-level=high

      - name: Validar codigo (Lint)
        run: npx eslint .

      - name: Ejecutar Pruebas (Jest)
        run: npm test

      - name: Build de Imagen Docker (Requisito AWS)
        run: docker build -t calculador-app:latest .